global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'Yellowstone'
    environment: 'development'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  # Yellowstone API metrics
  - job_name: 'yellowstone-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['yellowstone-api:9090']
    scrape_interval: 10s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  # PostgreSQL metrics (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  # Redis metrics (if using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  # Docker daemon metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['unix:///var/run/docker.sock']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  # Local Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
